### PR TITLE
Set reply-to by emailReplyTo option

### PR DESCRIPTION
**Pull request by Jako**
To set this option, the properties could i.e. be filled by

```
&emailReplyTo=`[[!getReqParam? &name=`field2` &type=`POST`]]`
```

### CODE REVIEW

**Comment by soydemadrid** [comment]
Hi thanks but I tried adding this in the formTpl and it doesn't seem to work. I have two Formz set up and one resource uses one and the other uses the other, so it could be that as both have different &name=`field` numbers/names that this won't work. Is there no way on the next release to just have Formz default to always reply to the email sender instead?

**Comment by Jako** [comment]
Do you have added this commit to your formz installation?

**Comment by soydemadrid** [comment]
ah sorry do I have to change the code? I haven't done this. But as I need the different forms to all work with their email sender this still wouldn't work would it? Also when will this be available from the Modx update manager as I would rather wait for the official upgrade if it comes available so I don't overwrite it later with other package manager upgrades. Thanks again.

**Comment by Jako** [comment]
Maybe Adido will accept my pull request. Until then you could use the changes on the 'Files changed' tab above (just two lines).

**Comment by soydemadrid** [comment]
ok thanks!

**Pull request closed without merging**
